title: Bharathi's Homepage 
description: "Success is not a destination, it is a journey..."
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-cayman 
button:
        text: Download CV
        url: https://github.com/Bharathi-Math/home/blob/183649e1dff321a5a9f321464f06238b02723381/index.md






header_pages:
 - index.md
 - aboutme.md
 - teaching.md
 - research.md
 - event.md
 - activities.md
 - gallery.md

sass:
  style: compressed

markdown: kramdown
plugins:
    - jekyll-sass-converter

    
# Link to the custom CSS file
assets:
  css: "style.css"

