title: Bharathi's Homepage 
description: "Success is not a destination, it is a journey..."
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-cayman

nav:
  - text: "Home"
    url: "/"
  - text: "About Me"
    url: "/about"  # Adjust this to your desired URL
  - text: "Teaching"
    url: "/teaching" 
  - text: "Research"
    url: "/research" 
  - text: "Events"
    url: "/event" 
  - text: "Activities"
    url: "/activitites"
  - text: "Gallery"
    url: "/gallery" 

 header_pages:
 - index.md
 - about.md
 - teaching.md
 - research.md
 - event.md
 - activities.md
 - gallery.md


sass:
  style: compressed

markdown: kramdown

# Link to the custom CSS file
assets:
  css: "styles.css"
