title: Bharathi's Homepage 
email: bharathit.math@gmail.com
description: "Success is not a destination, it is a journey..."
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-cayman 
github_username:   bharathit.math

header_pages:
 - home.md
 - aboutme.md
 - teaching.md
 - research.md
 - event.md
 - activities.md
 - gallery.md

sass:
  style: compressed

markdown: kramdown
plugins:
    - jekyll-sass-converter

    
# Link to the custom CSS file
assets:
  css: "style.css"

