title: Bharathi's Homepage 
description: Welcome to My Homepage!!!

theme: jekyll-theme-cayman

header_pages:
  - index.md
  - about.md

sass:
  style: compressed

markdown: kramdown

# Link to the custom CSS file
assets:
  css: "style.css"
