title: Bharathi's Homepage 
description: "Success is not a destination, it is a journey..."
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-cayman

header_pages:
 - about.md
 - home.md

sass:
  style: compressed


# Link to the custom CSS file
  css: "style.css"
