title: Bharathi's Homepage 
description: "Success is not a destination, it is a journey..."
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

header_pages:
 - index.md
 - about.md
 - teaching.md
 - research.md
 - event.md
 - activities.md
 - gallery.md

 <header class="page-header" role="banner">
      {% if site.github.is_project_page %}
        <a href="teaching" class="btn">Teaching</a>
      {% endif %}
      {% if site.show_downloads %}
        <a href="index" class="btn">Home</a>
        <a href="about" class="btn">About Me</a>
      {% endif %}
    </header>

