title: Bharathi's Homepage 
description: "Success is not a destination, it is a journey..."
show_downloads: false
github:
  is_project_page: true
theme: jekyll-theme-minimal

header_pages:
 - index.md
 - about.md
 - teaching.md
 - research.md
 - event.md
 - activities.md
 - gallery.md

sass:
  style: compressed

markdown: kramdown

# Link to the custom CSS file
assets:
  css: "style.css"
