title: Bharathi's Homepage 
description: "Success is not a destination, it is a journey..."
show_downloads: false
github:
is_project_page: false
google_analytics:
theme: jekyll-theme-cayman

header_pages:
 - index.md
 - about.md
 - teaching.md
 - research.md
 - event.md
 - activities.md
 - gallery.md


