title: Bharathi's Homepage 
description: Welcome to My Homepage!!!
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-cayman

navigation:
  name_over_title: true
  strip_par: true
  sanitize: true
  h_max: 3

