title: Hi... I'm Bharathi Thiruvengadam...
image: pho.png
description: Welcome to My Homepage!!!
show_downloads: false
github:
  is_project_page: false
theme: jekyll-theme-cayman

navigation:
  - title: Home
    url: /README
  - title: Bio
    url: /bio
  - title: Teaching
    url: /teaching
  - title: Research
    url: /research
  - title: Events
    url: /event
  - title: Activities
    url: /activities
